export const ALIEN_REFLECT_TIMES = 2;
export const ALIEN_HORZ_SPEED = 1;
export const ALIEN_DESCENT    = 40;
export const ALIEN_SHOOT_MIN  = 1500;
export const ALIEN_SHOOT_MAX  = 1000;
export const SHOOT_COOLDOWN   = 600;
export const PLAYER_LIVES        = 3;     // начальные жизни игрока
export const BONUS_SPAWN_EVERY   = 7000;  // новый бонус каждые ≈ 7 с
export const BONUS_PLAYER_MS     = 3000;  // усиление стрельбы игрока
export const BONUS_ALIENS_MS     = 2000;  // усиление стрельбы/скорости пришельцев
export const KILL_STREAK         = 3;     // каждые 5 убийств – «ярость» пришельцев
export const STREAK_BUFF_MS      = 5000;  // длительность этой «ярости»
export const BONUS_TIME_TO_LIVE      = 4000;  // время жизни бонуса на экране
export const ALIEN_PRICE      = 100;  // время жизни бонуса на экране
export const DEATH_PRICE      = 2000;  // время жизни бонуса на экране
export const RAPID_BULLET_SPEED      = 2.5;
export const BOTTOM_BULLET_SPEED      = .8;
export const PLAYER_BULLET_SPEED      = -6;
export const PLAYER_BONUS_BULLET_SPEED      = -8;
