name: Deploy static game to GitHub Pages
on:
  push:
    branches: [ main ]            # каждый пуш в main триггерит деплой
permissions:
  contents: read                 # нужно actions/checkout
  pages: write                   # разрешение писать в gh-pages
  id-token: write                # для OIDC-логина в Pages

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Клонируем репозиторий
      - uses: actions/checkout@v4

      # 2. Загружаем готовые файлы как артефакт Pages
      #    Флаг working-directory, чтобы путь был относительный к lab2/
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs                          # lab2/docs, см. defaults ниже
        working-directory: lab2

      # 3. Публикуем артефакт на GitHub Pages
      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4

    # Показываем итоговый URL в логах job’а
    outputs:
      page_url: ${{ steps.deploy.outputs.page_url }}